# Generated by Django 5.1.1 on 2024-11-25 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='titulo',
            new_name='nome',
        ),
    ]
