# Generated by Django 5.1.1 on 2024-11-25 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0002_rename_titulo_produto_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='autor',
            new_name='descricao',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
    ]
